# Generated by Django 2.2.1 on 2019-09-10 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190910_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 15, 58, 16, 729406, tzinfo=utc)),
        ),
    ]
